version: '3'
services:
  java-backend:
    image: adamino/grpc-chat-java-server:latest
    command: mvn exec:java -D exec.mainClass=dk.adamino.chat.ChatServer
    ports:
      - 9090:9090
    networks:
      - grpcmesh

  java-proxy:
    image: adamino/grpc-chat-java-proxy:latest
    ports:
      - 1337:1337
    networks:
      - grpcmesh

  nestjs-backend:
    image: adamino/grpc-chat-nestjs-server:latest
    ports:
      - 3000:3000
    networks:
      - grpcmesh

  nestjs-proxy:
    image: adamino/grpc-chat-nestjs-proxy:latest
    ports:
      - 1338:1338
    networks:
      - grpcmesh

  angular-client:
    image: adamino/grpc-chat-angular-client:latest
    depends_on:
      - java-backend
      - java-proxy
      - nestjs-backend
      - nestjs-proxy
    ports:
      - 4200:80
    networks:
      - grpcmesh

networks:
  grpcmesh: {}
